version: '3.9'

services:
  trading-account-manager:
    build: ./TradingAccountManager
    volumes:
      - ./TradingAccountManager:/app
    depends_on:
      - fastapi

  fastapi:
      build: ./FastAPI
      volumes:
        - ./FastAPI:/app
      depends_on:
        - mysql
      #ports:
      #  - 8080:80

  nginx:
    build: ./Nginx
    volumes:
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - fastapi

  mysql:
    build: ./DB
    #volumes:
    #  - ./DB:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306

  bot-a:
    build: ./Bot-A
    volumes:
      - ./Bot-A:/app
    depends_on:
      - fastapi  # Add this line if bot-a depends on fastapi
      - nginx
  
  bot-b:
    build: ./Bot-B
    volumes:
      - ./Bot-B:/app
    depends_on:
      - fastapi  # Add this line if bot-a depends on fastapi
      - nginx


      

  