version: '3.9'

services:
  trading-account-manager:
    build: ./TradingAccountManager
    volumes:
      - ./TradingAccountManager:/app

  fastapi:
      build: ./FastAPI
      volumes:
        - ./FastAPI:/app
      #ports:
      #  - 8080:80

  nginx:
    build: ./Nginx
    volumes:
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - fastapi

  bot-a:
    build: ./Bot-A
    volumes:
      - ./Bot-A:/app
    depends_on:
      - fastapi  # Add this line if bot-a depends on fastapi
      - nginx
  
  bot-b:
    build: ./Bot-B
    volumes:
      - ./Bot-B:/app
    depends_on:
      - fastapi  # Add this line if bot-a depends on fastapi
      - nginx


      

  