FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD root_password
ENV MYSQL_DATABASE your_database
ENV MYSQL_USER user
ENV MYSQL_PASSWORD your_password

#ADD ./my.cnf /etc/mysql/conf.d/my.cnf

EXPOSE 3306
#CMD ["--default-authentication-plugin=mysql_native_password"]
